### ISSUE TITLE
It changes pointers without asking

### ISSUE THREAD

**Issue by mateohideg2** [martinchrzan/ColorPicker#1]
Hi! I tested this program and it changed my device pointers without asking me so then I had to go to settings for fixing it.

**Comment by martinchrzan** [comment]
Hi, I don't really understand what is the issue here. Mouse cursor is changed when you open color picker to indicate that now you are in color picking mode, when you select a color, it will switch cursor back to your original one. 
Are you saying that it does not switch back when you select a color? 
Where would you want to see the option for not changing cursor at all? In settings?

**Comment by mateohideg2** [comment]
> Hi, I don't really understand what is the issue here. Mouse cursor is changed when you open color picker to indicate that now you are in color picking mode, when you select a color, it will switch cursor back to your original one.
> Are you saying that it does not switch back when you select a color?
> Where would you want to see the option for not changing cursor at all? In settings?

Yes

**Comment by mpagels** [comment]
Sorry to open this up again. But I have this problem as well. The app crashes and the cursor changed the "input" cursor symbol. I made a little gif for better understanding. After uninstall the cursor change stays.

![2020-10-09-11-27-44](https://user-images.githubusercontent.com/54703643/95567362-1f49de80-0a23-11eb-9463-a32a3ff688f0.gif)

**Comment by martinchrzan** [comment]
Hi, sorry to hear that you are hitting this issue. 
Unfortunately, when the app crashes, or even when you uninstall, I cannot change the cursor to the default one again. 
To fix that, you can do following:

In mouse pointer settings, just change pointer size from 1 to any number and then back to 1. By doing so, windows will reset to default one and it will correct all other pointers.
![image](https://user-images.githubusercontent.com/11967522/95568119-24f3f400-0a24-11eb-9a43-3195b8b79b51.png)

If you are hitting this issue, you can disable changing mouse pointer completely in the Color Picker settings.
Regarding the crash, can you show me the logs when the crash happened that are here - "%appdata%\ColorPicker" ? 
Thanks a lot!

**Comment by mpagels** [comment]
Here you are:

ERROR: 00:58:14.2824723
    [Method]: ChangeCursor [Class]: CursorManager
    Failed to change cursor
Der Wert darf nicht NULL sein.
Parametername: value
Inner exception: 

Stack trace: 
   bei Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   bei Microsoft.Win32.Registry.SetValue(String keyName, String valueName, Object value, RegistryValueKind valueKind)
   bei ColorPicker.Mouse.CursorManager.ChangeCursor(String curFile, String cursorRegistryName)
ERROR: 00:58:14.2934719
    [Method]: ChangeCursor [Class]: CursorManager
    Failed to change cursor
Der Wert darf nicht NULL sein.
Parametername: value
Inner exception: 

Stack trace: 
   bei Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   bei Microsoft.Win32.Registry.SetValue(String keyName, String valueName, Object value, RegistryValueKind valueKind)
   bei ColorPicker.Mouse.CursorManager.ChangeCursor(String curFile, String cursorRegistryName)
