### ISSUE TITLE
The shortcut in PowerToys didn't wrok Frequently.

### ISSUE THREAD

**Issue by MZhao-ouo** [martinchrzan/ColorPicker#14]
I often use the ColorPicker but the shortcut can't work normaly. 
I don't know it's because Win11 or others. 
I must trun the enable button off and on to solve it.
![image](https://user-images.githubusercontent.com/70903329/146662258-de0835c8-6482-477c-91a7-68749b978004.png)

**Comment by martinchrzan** [comment]
This project is using a different implementation for keyboard activation than PowerToys, please open this issue on their side. (I see you already did - https://github.com/microsoft/PowerToys/issues/15068)

**Comment by MZhao-ouo** [comment]
> 

Yeah !  Thanks !
