### ISSUE TITLE
 [Feature Request] Add RGB565 option

### ISSUE THREAD

**Issue by krizkontrolz** [martinchrzan/ColorPicker#16]
Hi Martin,
Are you planning to, or would you consider, adding a feature to be able to show the RGB565 (16-bit) color code (both Hex and Decimal)?
There are separate tools for doing this (e.g., http://www.barth-dev.de/online/rgb565-color-picker/), but it would be useful to have all options in one color picker (especially the picker that is already part of PowerTools).
Regards,
Kriz

**Comment by martinchrzan** [comment]
This has been now added, please see - [1.2.1](https://github.com/martinchrzan/ColorPicker/releases/tag/1.2.1)

**Comment by krizkontrolz** [comment]
Great, thanks @martinchrzan
