### ISSUE TITLE
Different decimal value

### ISSUE THREAD

**Issue by MohamadHalloway** [martinchrzan/ColorPicker#17]
Hello Martin,

as the program uses the following formula to calculate RGB -> Dec:
dec(c) = R + G*256 + B*256*256

I noticed there are some programs, that calculate the dec value the other way round:
dec(c) = B + G*256 + R*256*256

It would be very helpful if you would add it as an option among the other color formats
![grafik](https://user-images.githubusercontent.com/43098999/176653623-764b360f-ac47-4cec-97af-51f468b1a269.png)

Best regards

**Comment by martinchrzan** [comment]
This color format has been added, please see [1.2.1](https://github.com/martinchrzan/ColorPicker/releases/tag/1.2.1)
