### ISSUE TITLE
Copied text is in uppercase, should be lowercase

### ISSUE THREAD

**Issue by elibroftw** [martinchrzan/ColorPicker#2]
Awesome tool, only using it because Snip & Sketch doesn't have the color picker feature.
When I click copy color code, it copies the upper case code which is bad practice in web development because upper case characters are harder to read than lower case characters.
Lowercase should either be the default or have options to let the user decide which case to choose

**Comment by martinchrzan** [comment]
@elibroftw Thanks for the suggestion! Copied HEX is now in lowercase (since version 1.0.5)
