### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by TheYocks** [martinchrzan/ColorPicker#20]
Hello there, and wow, amazing work !! 

Do you think it would be possible to add a feature that gather the average color of an area of pixel instead of only 1 pixel ? 
I work in an environment where this could really come in handy to recreate the color of a subject we took a picture of. (calibration of picture is already figured out).

Thank you !

**Comment by martinchrzan** [comment]
@TheYocks I have added a new feature that will allow you to select an area from which you want an average color. Check it out!

**Comment by TheYocks** [comment]
Amazing !! I will try that out as soon as I get home 👍🤟

**Comment by TheYocks** [comment]
Well the function is just even better than what I was expecting !

Now do you think we could add "Lab"  as a color format ?
