### ISSUE TITLE
BUG: Color format in settings

### ISSUE THREAD

**Issue by Limo96** [martinchrzan/ColorPicker#28]
Hi, thanks for the tool :D

I wanted to report a problem when trying to use the same name in color formats, in settings.

As color formats I have:
HEX ffe4b5
RGB 255; 228; 181
HSV hsv(38, 29%, 100%)

I wanted to have two RGB with ; and with ,. When I go to rename HSV to RGB the settings crash as soon as I press B.
![image](https://github.com/martinchrzan/ColorPicker/assets/1770735/8af7e1c1-fbfa-46ca-b7b0-472151f9e2e2)

**Comment by martinchrzan** [comment]
Can you please report this directly in [PowerToys](https://github.com/microsoft/PowerToys) since this functionality is implemented only there, not in my ColorPicker which is hosted here?

**Comment by Limo96** [comment]
Yes, no problem
