### ISSUE TITLE
Feature Request: Plot on a Color Wheel

### ISSUE THREAD

**Issue by ossnorry** [martinchrzan/ColorPicker#29]
Your fantastic tool has become essential in my creative workflow, have you considered providing an option where it can plot the selected value on a rainbow color wheel so the user can easily see what colors they're move towards. Would be useful for things like video and photo editing. 

Example: 
![image](https://github.com/martinchrzan/ColorPicker/assets/53498446/e5c0000e-618a-4edc-b984-3b82e9800576)

**Comment by martinchrzan** [comment]
Thanks for using the tool and the feedback! 
I am not really sure how you would imagine this to work? Where would this color wheel appear? While you are picking a color or after you picked it?

**Comment by martinchrzan** [comment]
No response, closing the issue
