### ISSUE TITLE
please add hsv as another option for rgb/hex

### ISSUE THREAD

**Issue by panyuhang93** [martinchrzan/ColorPicker#3]

**Comment by martinchrzan** [comment]
In what string format would you want to have it?

**Comment by panyuhang93** [comment]
Thank you 
I think is Hue，Saturation，Value
like black hsv(0,0,0) 
        White hsv(0,0,100)
This is a list http://www.ebaomonthly.com/window/photo/lesson/colorList.htm
I use hsv for drawing on photoshop and sai2

**Comment by martinchrzan** [comment]
Latest version adds hsv and hsl color formats, check it out!

**Comment by panyuhang93** [comment]
It’s late,but Thank you very much.
