### ISSUE TITLE
Color Picker is laggy

### ISSUE THREAD

**Issue by symonxdd** [martinchrzan/ColorPicker#36]
Just what the title says. Upon activating Windows Key + Shift + C (default keybind), the little interface showing the color, lags when move the mouse.

I'm using this tool from PowerToys.

There's another tool I've been using for years, [Instant Eyedropper](http://instant-eyedropper.com/), which is not laggy and makes it a great competitor with this tool 😆

**Comment by martinchrzan** [comment]
Please report this issue directly to [PowerToys](https://github.com/microsoft/PowerToys) page, it has different look and implementation than mine that is hosted here. Also please test my implementation [release](https://github.com/martinchrzan/ColorPicker/releases/tag/1.3.0) if it has the same behaviour.
