### ISSUE TITLE
Long freezes when copying text to the clipboard when using Clipjump.

### ISSUE THREAD

**Issue by vctsvz** [martinchrzan/ColorPicker#4]
Hangs for a few seconds and cursor stays unchanged after copying to clipboard when used [Clipjump](http://clipjump.sourceforge.net). 

Quite a specific program, but extremely convenient and quite popular in narrow geek circles.

> Clipjump is a multiple clipboard management utility for Windows. It was built to make working with multiple clipboards super fast and super easy. The program records changes in the system clipboard, stores them without any limits and provides innovative ways to work with them.

**Comment by martinchrzan** [comment]
@vctsvz Thank you, I have now fixed this issue and will do a release shortly
