### ISSUE TITLE
Does not seem to work on WPF applications

### ISSUE THREAD

**Issue by jcbaar** [martinchrzan/ColorPicker#43]
When I open the picker (I'm using it from PowerToys btw) using the hotkey it won't show when a WPF window is the active window. If I open it from another app and the picker is active it will not select a color from a WPF application window.

Don't know if it is relevant but I'm running Windows 11 23H2 on a remote desktop.

**Comment by martinchrzan** [comment]
Is it all WPF apps or just some specific one? This sounds like the app is
stealing events - key shortcuts when activating it and mouse clicks when
selecting. Could that app have a global hook and not bubbling events up
after handling them?

**Comment by jcbaar** [comment]
I have noticed this on my own WPF apps but also Visual Studio. What I did forget to mention is that my apps use custom window chrome just as Visual Studio seem does. I use the WindowChrome class which does perform quite a bit of hook magic. My guess would be that Visual Studio does something similar.

[https://github.com/oysteinkrog/WPF-Shell-Integration-Library/blob/master/Microsoft.Windows.Shell/WindowChrome.cs](url)
[https://github.com/oysteinkrog/WPF-Shell-Integration-Library/blob/master/Microsoft.Windows.Shell/WindowChromeWorker.cs](url)

Honestly I did not check on a WPF app using a "normal" window,

**Comment by jcbaar** [comment]
Sorry,

Wrong links...

[https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Shell/WindowChrome.cs](url)
[https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Shell/WindowChromeWorker.cs](url)

**Comment by jcbaar** [comment]
Well after a little more research and a reboot it works just fine. I noticed this issue after PowerToys updated while my app and VS where already running so my guess is that the update re-installed your hook(s) after the hooks created by the WindowChrome class. Rebooting made sure PowerToys was started first and that probably made it work.

I think this issue can be closed.

**Comment by martinchrzan** [comment]
Can you try the colorpicker from this repo? I use hooks slightly differently
