### ISSUE TITLE
FeatureRequest: Add vec3 or vec4 mode for shader debugging.

### ISSUE THREAD

**Issue by gonnavis** [martinchrzan/ColorPicker#5]
Could you please add a new vec4 mode to facilitate the shader debugging?

This mode will map 0,255 to 0,1.

For example:

rgb(0, 127, 255) to vec4(0, .5, 1, 1)

rgb(100, 50, 75) to vec4(0.392, 0.196, .294, 1)

**Comment by martinchrzan** [comment]
Will do, thanks for a suggestion
