### ISSUE TITLE
After use the colorpicker,my windows cursor changed permanently

### ISSUE THREAD

**Issue by T1m3ch0** [martinchrzan/ColorPicker#6]
just as the pic shows,how can I return back to windows default cursor?
![IMG_20201206_103424](https://user-images.githubusercontent.com/31351200/101269930-ddcd7980-37ae-11eb-8f56-310a6d1fe7dc.jpg)

**Comment by martinchrzan** [comment]
Hi, unfortunately switching of cursor does not seems to be stable as reported by others as well, I suggest you to turn this option off in the settings of color picker, to fix it, please follow instructions in - #1

**Comment by nixprosoft** [comment]
The same issie.

**Comment by martinchrzan** [comment]
Can you please share logs from - go to this location - %appdata%\ColorPicker - clean all logs that you have there, try to replicate that issue afterwards and please share create log file here. Thanks!

**Comment by arnofly** [comment]
Same issue for me...

**Comment by arnofly** [comment]
ERROR: 21:51:03.2580248
    [Method]: ChangeCursor [Class]: CursorManager
    Failed to change cursor
La valeur ne peut pas être null.
Nom du paramètre : value
Inner exception: 

Stack trace: 
   à Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   à Microsoft.Win32.Registry.SetValue(String keyName, String valueName, Object value, RegistryValueKind valueKind)
   à ColorPicker.Mouse.CursorManager.ChangeCursor(String curFile, String cursorRegistryName)
ERROR: 21:51:03.2630200
    [Method]: ChangeCursor [Class]: CursorManager
    Failed to change cursor
La valeur ne peut pas être null.
Nom du paramètre : value
Inner exception: 

Stack trace: 
   à Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   à Microsoft.Win32.Registry.SetValue(String keyName, String valueName, Object value, RegistryValueKind valueKind)
   à ColorPicker.Mouse.CursorManager.ChangeCursor(String curFile, String cursorRegistryName)

**Comment by martinchrzan** [comment]
@T1m3ch0 @nixprosoft @arnofly  I have made fixes in [1.1.2 release](https://github.com/martinchrzan/ColorPicker/releases/tag/1.1.2), please check it out
