### ISSUE TITLE
Settings buttons not visible when using Windows light theme

### ISSUE THREAD

**Issue by Paper-Folding** [martinchrzan/ColorPicker#7]
#### When starting the latest version, the color theme is mixed up with black which is unfriendly to use and the hotkey cannot be set due to missing button "ok" and "cancel" on UI.

**Comment by martinchrzan** [comment]
@Paper-Folding thank you for finding this, this issue does not occur when using windows dark theme, I will fix it!

**Comment by martinchrzan** [comment]
Resolved in the release 1.1.1

**Comment by Paper-Folding** [comment]
Thanks for fix this, problem solved!
