### ISSUE TITLE
Add cusom color names

### ISSUE THREAD

**Issue by kiwina** [martinchrzan/ColorPicker#8]
Hi a suggestion for web developers is to add a translation of colors to framework color names.
Specifically here i mean tailwind css but, but it could be implemented for several frameworks.
i have something similar as a browser extension but it be great to implement in this tool i use all the time.

**Comment by Thomas-Bagnolati** [comment]
Hi, I get the same suggestion. I really like to use this Color Picker but it need to can put name as color to reference it. 
An other cool think will be to can create folder to make multiple colors schemes / colors groupes.

Thanks for your work !

**Comment by nelsondani** [comment]
[]() `[030609]() [https://visualstudio.microsoft.com/wp-content/uploads/2019/12/random-swim-lane-01.svg]() `

**Comment by martinchrzan** [comment]
Thanks a lot for input and suggestions, it took a little longer but now you can see the name of a color (from the version 1.3.0), just enable it in the settings!
